In [7]:
# completeness

import pandas as pd
df = pd.DataFrame({'order_id':[1001,1002],
                   'customer_id':['c101',None],
                   'amount':[400,500]})
df

   order_id customer_id  amount
0      1001        c101     400
1      1002        None     500

In [ ]:
df.isnull().sum()

order_id       0
customer_id    1
amount         0
dtype: int64

In [8]:
# Accuracy
df = pd.DataFrame({'revenue':[500,300,-90], 'Order_ID':[101,102,304]})
df

   revenue  Order_ID
0      500       101
1      300       102
2      -90       304

In [9]:
bad_rows = df[(df.revenue < 0)]
bad_rows

   revenue  Order_ID
2      -90       304

In [ ]:
# consistency
df = pd.DataFrame({'city':['delhi', 'DELHI','Mumbai', 'MUMBAI','DELhi'], 'Order_ID':[101,102,304,111,222]})
df

     city  Order_ID
0   delhi       101
1   DELHI       102
2  Mumbai       304
3  MUMBAI       111
4   DELhi       222

In [ ]:
df_new = df.copy() # copy function will ensure it creases a seperate copy at different memory address
df_new

     city  Order_ID
0   delhi       101
1   DELHI       102
2  Mumbai       304
3  MUMBAI       111
4   DELhi       222

In [ ]:
df_new['city'] = df_new['city'].str.upper()
df_new

     city  Order_ID
0   DELHI       101
1   DELHI       102
2  MUMBAI       304
3  MUMBAI       111
4   DELHI       222

In [ ]:
df_new['city'] = df_new['city'].map({'DELHI':0,'MUMBAI':1})
df_new

   city  Order_ID
0     0       101
1     0       102
2     1       304
3     1       111
4     0       222

In [10]:
df = pd.DataFrame({'order_id':[101,102,101,101,103,104]})
df

   order_id
0       101
1       102
2       101
3       101
4       103
5       104

In [11]:
duplicated = df[(df.duplicated())]
duplicated

   order_id
2       101
3       101

In [3]:
df = pd.read_csv(r'/content/data.csv')
df

FileNotFoundError: [Errno 2] No such file or directory: '/content/data.csv'

In [ ]:
# - Order ID - missing value
#            - duplicate entry
# - customer_id - missing value (combination of order_id and customer_id should be unique)
# - revenue - cannot